// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using samuel_leutner_DR4_TP3_dotNet.data;

#nullable disable

namespace samuel_leutner_DR4_TP3_dotNet.Migrations
{
    [DbContext(typeof(CityBreaksContext))]
    [Migration("20250604012527_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("samuel_leutner_DR4_TP3_dotNet.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Guarapuava"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Curitiba"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 4,
                            Name = "London"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 5,
                            Name = "Paris"
                        });
                });

            modelBuilder.Entity("samuel_leutner_DR4_TP3_dotNet.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "BRA",
                            CountryName = "Brazil"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "USA",
                            CountryName = "United States"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "CAN",
                            CountryName = "Canada"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "GBR",
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "FRA",
                            CountryName = "France"
                        });
                });

            modelBuilder.Entity("samuel_leutner_DR4_TP3_dotNet.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Hotel Central",
                            PricePerNight = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Pousada do Lago",
                            PricePerNight = 120.50m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Name = "Apartamento Batel",
                            PricePerNight = 200.00m
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            Name = "Luxury Condo Times Square",
                            PricePerNight = 500.00m
                        },
                        new
                        {
                            Id = 5,
                            CityId = 4,
                            Name = "Hollywood Hills Villa",
                            PricePerNight = 750.00m
                        },
                        new
                        {
                            Id = 6,
                            CityId = 5,
                            Name = "Downtown Studio",
                            PricePerNight = 180.00m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 6,
                            Name = "Cozy Flat near Big Ben",
                            PricePerNight = 300.00m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 7,
                            Name = "Eiffel Tower View Apartment",
                            PricePerNight = 450.00m
                        });
                });

            modelBuilder.Entity("samuel_leutner_DR4_TP3_dotNet.Models.City", b =>
                {
                    b.HasOne("samuel_leutner_DR4_TP3_dotNet.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("samuel_leutner_DR4_TP3_dotNet.Models.Property", b =>
                {
                    b.HasOne("samuel_leutner_DR4_TP3_dotNet.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("samuel_leutner_DR4_TP3_dotNet.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("samuel_leutner_DR4_TP3_dotNet.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
